aws_region      = "eu-west-2"
az_a            = "eu-west-2a"
az_b            = "eu-west-2b"
environment     = "dev"
vpc_cidr        = "10.0.0.0/16"
container_name  = "threatmod-app-container-serverless"
container_image = "891377356090.dkr.ecr.eu-west-2.amazonaws.com/ecs-threat-composer-app:latest"
container_image_tag = "latest"
ECR_REPOSITORY = "ecs-threat-composer-app"
#inputed for dev infra and is safe