
# multistage docker build : builder stage

FROM node:18 AS builder

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build

# multistage docker build : runtime

FROM node:18-slim AS runtime

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3003

RUN  useradd -m hassan

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production && yarn cache clean

COPY --from=builder /app/build ./build
COPY --from=builder /app/server.js ./server.js

RUN chown -R hassan:hassan /app
USER hassan

EXPOSE 3003

CMD ["node","./server.js"]