# multistage docker build
# builder stage

FROM node:18 AS builder

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build

# this is the runtime
FROM node:18-slim AS runtime

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3003

RUN  useradd -m hassan

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production && yarn cache clean

COPY --from=builder /app/build ./build
COPY --from=builder /app/server.js ./server.js

# COPY --from=builder /app/package.json ./package.json
# COPY --from=builder /app/node_modules ./node_modules

RUN chown -R hassan:hassan /app
USER hassan

EXPOSE 3003

CMD ["node","./server.js"]