  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

  env:
    AWS_REGION: eu-west-2
    ECR_REPOSITORY: ecs-threat-composer-app
    ECS_SERVICE: threatmod-cluster-service
    ECS_CLUSTER: threatmod-cluster-main
    ECS_TASK_DEFINITION: .aws/task-definition.json
    CONTAINER_NAME: threatmod-app-container-serverless

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Fmt
        working-directory: infra
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: infra
        run: terraform validate

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan \
            -var="ECR_REPOSITORY=${{ env.ECR_REPOSITORY }}" \
            -var="ECR_REGISTRY=${{ secrets.ECR_REGISTRY }}" \
            -var="container_image_tag=latest" \
            -var="task_role_arn=${{ secrets.TASK_ROLE_ARN }}" \
            -var="execution_role_arn=${{ secrets.EXECUTION_ROLE_ARN }}"


      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve \
            -var="ECR_REPOSITORY=${{ env.ECR_REPOSITORY }}" \
            -var="ECR_REGISTRY=${{ secrets.ECR_REGISTRY }}" \
            -var="container_image_tag=latest" \
            -var="task_role_arn=${{ secrets.TASK_ROLE_ARN }}" \
            -var="execution_role_arn=${{ secrets.EXECUTION_ROLE_ARN }}"