name: Deploy to Amazon ECS

on:
  workflow_run:
    workflows: ["CI Workflow"]
    types: [completed]
    branches: [main]
  workflow_dispatch:


# Only one deploy at a time - prevents race conditions
# If two builds finish back-to-back, only the latest deploy runs
concurrency:
  group: deploy-production
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read


# env:
#   AWS_REGION: eu-west-2                      # AWS region
#   ECR_REPOSITORY: ecs-threat-composer-app     # Your ECR repository
#   ECS_SERVICE: threatmod-cluster-service       # Your ECS service name
#   ECS_CLUSTER: threatmod-cluster-main       # Your ECS cluster name
#   ECS_TASK_DEFINITION: .aws/task-definition.json  # Task definition file path
#   CONTAINER_NAME: threatmod-app-container-serverless  # Name of the container in the task definition

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            aws-region: ${{ secrets.AWS_REGION }}

      - name: Render task definition with new image
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ secrets.ECS_TASK_DEFINITION }}
          container-name: ${{ secrets.CONTAINER_NAME }}
          image: ${{ steps.ecr-login.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:sha-${{ github.event.workflow_run.head_sha }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: true