name: CI Workflow

on:
  workflow_run:
    workflows: ["Terraform Deploy"]
    types: [completed]
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write   # Required for OIDC authentication with AWS
  contents: read    # Required for actions/checkout

env:
  AWS_REGION: eu-west-2                      # AWS regionnn
  ECR_REPOSITORY: ecs-threat-composer-app     # Your ECR repository
  ECS_SERVICE: threatmod-cluster-service       # Your ECS service name
  ECS_CLUSTER: threatmod-cluster-main       # Your ECS cluster name
  ECS_TASK_DEFINITION: infra/.aws/task-definition.json  # Task definition file path
  CONTAINER_NAME: threatmod-app-container-serverless  # Name of the container in the task definition

jobs:
  build-and-push:
    name: Build, Scan & Push
    runs-on: ubuntu-latest

    steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Debug SHA
            run: echo "GitHub SHA:${{ github.sha }}"

          - name: Build Docker image
            id: build-image
            run: |
              docker build -t ${{ env.ECR_REPOSITORY }}:sha-${{ github.sha }} ./app
              echo "image=${{ env.ECR_REPOSITORY }}:sha-${{ github.sha }}" >> $GITHUB_OUTPUT

          - name: Use image output
            run: |
              echo "The built image is ${{ steps.build-image.outputs.image }}"

          # - name: Scan image with Grype
          #   uses: anchore/scan-action@v6
          #   with:
          #     image: "${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
          #     fail-build: "true"
          #     severity-cutoff: high
          #     output-format: table

          # - name: Upload Grype scan results
          #   if: always()
          #   uses: github/codeql-action/upload-sarif@v3
          #   with:
          #     sarif_file: ${{ steps.scan.outputs.sarif }}

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              role-to-assume: ${{ secrets.CICD_ECS_ROLE }}
              aws-region: ${{ env.AWS_REGION }}

          - name: Login to Amazon ECR
            id: ecr-login
            uses: aws-actions/amazon-ecr-login@v2

          - name: Tag and push image to ECR
            env:
              ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
            run: |
              docker tag ${{ env.ECR_REPOSITORY }}:sha-${{ github.sha }} \
                $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:sha-${{ github.sha }}

              docker tag ${{ env.ECR_REPOSITORY }}:sha-${{ github.sha }} \
              $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest

              docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:sha-${{ github.sha }}
              docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest

              echo "### Image pushed :white_check_mark:" >> $GITHUB_STEP_SUMMARY
              echo "**Image:** \`$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:sha-${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY