name: CI Workflow

on:
  workflow_run:
    workflows: ["Deploy Infra and update ECS Service"]
    types: [completed]
    branches: [main]
  push:
    branches: [main]
    paths:
      - 'app/**'
      - '.github/workflows/ci.yaml'
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  security-events: write

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: ecs-threat-composer-app
  ECS_SERVICE: threatmod-cluster-service
  ECS_CLUSTER: threatmod-cluster-main
  ECS_TASK_DEFINITION: infra/.aws/task-definition.json
  CONTAINER_NAME: threatmod-app-container-serverless

jobs:
  build-and-push:
    name: Build, Scan & Push
    runs-on: ubuntu-latest

    steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Build Docker image
            id: build-image
            run: |
              docker build -t ${{ env.ECR_REPOSITORY }}:sha-${{ github.sha }} ./app
              echo "image=${{ env.ECR_REPOSITORY }}:sha-${{ github.sha }}" >> $GITHUB_OUTPUT

          - name: Use image output
            run: |
              echo "The built image is ${{ steps.build-image.outputs.image }}"

          - name: Scan image with Grype
            uses: anchore/scan-action@v6
            with:
              image: "${{ env.ECR_REPOSITORY }}:sha-${{ github.sha }}"
              fail-build: "true"
              severity-cutoff: high
              output-format: sarif

          - name: Upload Grype scan results
            if: always()
            uses: github/codeql-action/upload-sarif@v4
            with:
              sarif_file: ${{ steps.scan.outputs.sarif }}

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              role-to-assume: ${{ secrets.CICD_ECS_ROLE }}
              aws-region: ${{ env.AWS_REGION }}

          - name: Login to Amazon ECR
            id: ecr-login
            uses: aws-actions/amazon-ecr-login@v2

          - name: Tag and push image to ECR
            env:
              ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
            run: |
              docker tag ${{ env.ECR_REPOSITORY }}:sha-${{ github.sha }} \
                $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:sha-${{ github.sha }}

              docker tag ${{ env.ECR_REPOSITORY }}:sha-${{ github.sha }} \
              $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest

              docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:sha-${{ github.sha }}
              docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:latest

              echo "### Image pushed :white_check_mark:" >> $GITHUB_STEP_SUMMARY
              echo "**Image:** \`$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:sha-${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY